server:
  port: 8080
  servlet:
    context-path: /swp

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/data"
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
jwt:
  signerKey: "1Ln55lu2teW6wbb2nd3sLkHUQgql0e/avY0TCtXgEkERCDXm6tB6m64jXVXf43jn"
  valid-duration: 3600  #second
  refreshable-duration: 36000 #second
openapi:
  title: API document
  version: v1.0.0
  description: API service
  serverUrl: http://localhost:8080/swp
  serverName: Test Server
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
supabase:
  url: "https://qtlwqfhffuffjcgkgity.supabase.co"
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0bHdxZmhmZnVmZmpjZ2tnaXR5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDAyNjI5NCwiZXhwIjoyMDU1NjAyMjk0fQ.sRVChWMFDxUiHZcsAbaORZ84gLP3eJ47GTDdrQFYGN4"
  bucket: "ImageBucket"